---
# With thanks to https://milliams.com/posts/2020/ansible-certificate-authority/

- name: install crypto library for openssl_* modules
  become: true
  become_user: root
  yum:
    state: installed
    name: python3-cryptography

- name: Create the CA directory
  file:
    path: "{{ ca_dir }}"
    state: directory
    mode: '0750'

- name: Create CA key
  openssl_privatekey:
    path: "{{ ca_dir }}/simpleca.key"
  register: ca_key

- name: Create the CA CSR
  openssl_csr:
    path: "{{ ca_dir }}/simpleca.csr"
    privatekey_path: "{{ ca_key.filename }}"
    common_name: "simpleca"
    basic_constraints:
    - "CA:TRUE"
  register: ca_csr

- name: Sign the CA CSR
  openssl_certificate:
    path: "{{ ca_dir }}/simpleca.crt"
    csr_path: "{{ ca_csr.filename }}"
    privatekey_path: "{{ ca_key.filename }}"
    provider: selfsigned
  register: ca_crt

- name: Create a private key for {{ cert_user }}
  openssl_privatekey:
    path: "{{ cert_dir }}/{{ cert_user }}.key"
  register: user_key

- name: Create a CSR for {{ cert_user }}
  openssl_csr:
    path: "{{ cert_dir }}/{{ cert_user }}.csr"
    privatekey_path: "{{ user_key.filename }}"
    common_name: "{{ cert_name }}"
    subject_alt_name:
      - "DNS:{{ cert_name }}"
      - "DNS:{{ standalone_host }}"
      - "IP:{{ public_api }}"
      - "IP:{{ control_plane_ip }}"
  register: user_csr

- name: Sign the CSR for {{ cert_user }}
  openssl_certificate:
    path: "{{ cert_dir }}/{{ cert_user }}.crt"
    csr_path: "{{ user_csr.filename }}"
    provider: ownca
    ownca_path: "{{ ca_crt.filename }}"
    ownca_privatekey_path: "{{ ca_key.filename }}"
