---
- hosts: localhost
  name: Deploy the CA
  gather_facts: false
  vars_files: vars/defaults.yaml
  roles:
    - name: Deploy the CA with the simplaca role
      role: simpleca
      vars:
        cert_user: quay
        cert_name: "{{ standalone_host }}"
