---
- hosts: standalone
  become: true
  become_user: stack
  gather_facts: false
  tasks:
  - name: Run post-install script # noqa 305
    shell: "{{ post_install }}"
    when: post_install is defined
