---
- hosts: standalone
  gather_facts: false
  vars_files: vars/defaults.yaml

  tasks:

    - name: Check if inventory matches with standalone_host
      assert:
        that:
          - standalone_host == ansible_host
        fail_msg: >
          Your inventory does not match with standalone_host set to '{{ standalone_host }}'
          and ansible_host in the inventory set to '{{ ansible_host }}', which could
          lead to a deployment on the wrong host
        success_msg: 'standalone_host matches with ansible_host, target is valid'

    - name: Check if control plane IP is different from the public IP
      assert:
        that:
          - control_plane_ip != public_api
        fail_msg: >
          You must set different IP addresses for control_plane_ip and public_api otherwise
          the deployment of OpenStack will fail.
        success_msg: 'control plane IP is different from the public IP'
