name: Ansible Lint
on:
  pull_request:
    paths:
      - playbooks/**.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checks-out the repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ansible-lint
        run: python3 -m pip install ansible-dev-tools --user

      - name: Install dependency
        run: ansible-galaxy collection install -r requirements.yaml

      # This works around the lint error from `ansible-playbook --syntax-check -vv playbooks/install_stack.yaml`
      # [ERROR]: Could not find specified file in role, its 'tasks/' is not usable.
      - name: Prepare redhat-subscription
        run: git clone --depth 1 --branch 1.3.0 https://opendev.org/openstack/ansible-role-redhat-subscription.git $HOME/.ansible/roles/redhat-subscription

      - name: Run lint
        run: export ANSIBLE_COLLECTIONS_PATH=$HOME/.ansible/collections;
